version: 2.0
jobs:
  build:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: apt-get -y update
      - run: apt-get -y install build-essential
      - run: apt-get -y install cmake
      - run: apt-get -y install libboost-all-dev
      - run: apt-get -y install aptitude
      - run: git clone https://github.com/zeromq/libzmq
      - run: cd libzmq
      - run: mkdir cmake-build && cd cmake-build
      - run: cmake .. && make -j 4
      - run: make test && make install && sudo ldconfig
      - run: cd ..
      - run: make
