version: 2.0
jobs:
  build:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: apt-get -y update
      - run: apt-get -y install build-essential
      - run: add-apt-repository ppa:george-edison55/cmake-3.x
      - run: apt-get -y update      
      - run: apt-get -y install cmake
      - run: make
