version: 2.0
jobs:
  build:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: apt-get -y update
      - run: apt-get -y install build-essential
      - run: apt-get -y install cmake
      - run: apt-get -y install libboost-all-dev
      - run: apt-get -y install aptitude
      - run: wget https://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/Debian_9.0/Release.key -O- | apt-key add
      - run: apt-get -y install libzmq3-dev
      - run: make
