version: 2.0
jobs:
  build:
    - docker
      #- image: gcc:latest
    steps:
      - checkout
      #- run: apt-get -y update
      #- run: wget -O boost_1_66_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.66.0/boost_1_66_0.tar.gz/download
      #- run: apt-get -y install aptitude
      #- run: apt-get -y install libzmq3-dev
      #- run: apt-get install -y build-essential g++ python-dev autotools-dev libicu-dev build-essential libbz2-dev libboost-all-dev openssl libssl-dev libunwind8-dev liblzma-dev libreadline6-dev libldns-dev libexpat1-dev doxygen graphviz
      #- run: apt-get -y install cmake
      #- run: make
      - run: docker build -t magnustiberius/monero .
      - run: docker login -u="$DOCKERID" -p="$DOCKERIDPWD"
      - run: docker push magnustiberius/monero
